name: toggleable
description: Helps maintaining the state which can toggle. It provides various of helper methods.

homepage: https://github.com/Hwan-seok/toggleable
repository: https://github.com/Hwan-seok/toggleable
issue_tracker: https://github.com/Hwan-seok/toggleable/issues

version: 1.0.2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  easy_debounce: ^2.0.2+1

dev_dependencies:
  lints: ^2.0.0
  dartdoc: ^6.0.1
  test: any
